### ISSUE TITLE
Requires WinUSB install?

### ISSUE THREAD

**Issue by jdpigeon** [urish/noble-winrt#2]
Added this to my project and seem to have successfully installed and built all dependencies.

However, when I try to run any noble code I am hit with an error `LIBUSB_ERROR_NOT_SUPPORTED`

It appears that this is due to my computer not having the WinUSB driver installed: https://stackoverflow.com/questions/17350177/libusb-open-returns-libusb-error-not-supported-on-windows-7

Does this library require a USB dongle with WinUSB installed?

**Comment by urish** [comment]
It does not require a USB dongle nor WinUSB. WinUSB is probably a noble dependency that is not needed here. Make sure you only `require('noble-winrt')` and never `require('noble')` directly in your code.
